# Nginx config for Soft ICE Mini App
# Copy to: /etc/nginx/sites-available/app.utimoshi.ru

server {
    listen 80 default_server;
    server_name app.utimoshi.ru;

    root /var/www/app.utimoshi.ru;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
